version: '2'
services:
  web:
    image: jonidaedalus/naklei-app:latest
    volumes:
      - /opt/naklei-home:/opt/naklei-home
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379